config/routes.rb
Rails.application.routes.draw do

root 'pages#home'
get 'about', to: 'pages#about'

resources :articles

get 'signup', to: 'users#new'
resources :users, except: [:new]

get 'login', to: 'sessions#new'
post 'login', to: 'sessions#create'
delete 'logout', to: 'sessions#destroy'

resources :categories, except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10 }
  validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user and !current_user.admin?
        flash[:danger] = "You may only edit or delete your own articles"
        redirect_to root_path
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def require_admin
      if !logged_in? || (logged_in? && !current_user.admin?)
        flash[:danger] = "Only admins may perform that action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:username, :email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user and !current_user.admin?
        flash[:danger] = "You may only edit your own profile"
        redirect_to root_path
      end
    end

    def require_admin
      if logged_in? and !current_user.admin?
        flash[:danger] = "Only admin users may perform that action"
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img_circle")
  end
end

app/views/articles/_article.html.haml
- obj.each do |article|
  .row
    .col-xs-8.col-xs-offset-2
      .well.well-lg
        .article-title
          = link_to article.title, article_path(article)
        .article-body
          = truncate(article.description, length: 100)
          .article-meta-details
            %small
              Created by: 
              = article.user.username if article.user
              = time_ago_in_words(article.created_at)
              ago, last updated: 
              = time_ago_in_words(article.updated_at)
              ago
        - if article.categories.any?
          %p
            Categories: 
            = render article.categories
        - if logged_in? && (current_user == article.user || current_user.admin?)
          .article-actions
            = link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary"
            = link_to "Delete this article", article_path(article), method: :delete, data: { confirm: "Are you sure you want to permanently delete this article?" }, class: "btn btn-xs btn-danger"

app/views/articles/_form.html.haml
= render 'shared/errors', obj: @article
.row
  .col-xs-12
    = form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .col-form-label.col-sm-2
          = f.label :title
        .col-sm-8
          = f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true
      .form-group
        .col-form-label.col-sm-2
          = f.label :description
        .col-sm-8
          = f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article"
      .form-group
        .row
          .col-sm-8.col-sm-offset-2
            = f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb|
              - cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text}
      .form-group
        .center
          = f.submit class: "btn btn-submit", id: "submit"
    .center
      = link_to "Cancel request and return to articles listing", articles_path

app/views/articles/edit.html.haml
%h1(align="center") Edit existing article

= render 'form'

app/views/articles/index.html.haml
%h1(align="center") Listing all articles
%div(align="center")= will_paginate
= render 'article', obj: @articles
%div(align="center")= will_paginate

app/views/articles/new.html.haml
%h1(align="center") Create an article

= render 'form'

app/views/articles/show.html.haml
%h2(align="center") Title: #{@article.title}
.well.col-xs-8.col-xs-offset-2
  %ul.listing
    .row.center
      .col-md-4.col-md-offset-4
        %li.created-by Created by:
        %li= link_to gravatar_for(@article.user), user_path(@article.user)
        %li.article-title= link_to @article.user.username, user_path(@article.user)
        %li
          %small= pluralize(@article.user.articles.count, "article") if @article.user.articles
  %h4.center.description
    %strong Description:
  %hr
  = simple_format(@article.description)
  - if @article.categories.any?
    %p
      Categories: 
      = render @article.categories
  .article-actions
    - if logged_in? && (current_user == @article.user || current_user.admin?)
      = link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary"
      = link_to "Delete this article", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to permanently delete this article?" }, class: "btn btn-xs btn-danger"
    = link_to "View all articles", articles_path, class: "btn btn-xs btn-primary"

app/views/categories/_category.html.haml
%span.badge= link_to category.name, category_path(category)

app/views/categories/_form.html.haml
= render 'shared/errors', obj: @category
= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f|
  .form-group
    .col-form-label.col-sm-2
      = f.label :name
    .col-sm-8
      = f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true
  .form-group
    .center
      = f.submit class: "btn btn-submit btn-lg"
.center
  = link_to "Cancel request and return to categories listing", categories_path

app/views/categories/edit.html.haml
%h1(align="center") Edit category name
= render 'form'

app/views/categories/index.html.haml
%h1(align="center") Listing all categories
.center
  = will_paginate
  - @categories.each do |category|
    %ul.listing
      .row
        .well.col-md-4.col-md-offset-4
          %li.article-title
            = link_to "#{category.name}", category_path(category)
          %li
            %small= pluralize(category.articles.count, "article")
  = will_paginate

app/views/categories/new.html.haml
%h1(align="center") Create new category
= render 'form'

app/views/categories/show.html.haml
%h1(align="center")= "Category: " + @category.name
- if logged_in? && current_user.admin?
  .center
    %span.badge.edit-category-name= link_to "Edit category name", edit_category_path(@category)
%div(align="center")= will_paginate @category_articles
= render 'articles/article', obj: @category_articles
%div(align="center")= will_paginate @category_articles

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    & Copyright © #{link_to 'Acropoiesis Media Group LLC', 'http://acropoiesis.com'}
  %nav
    %ul
      %li= link_to 'About', about_path

app/views/layouts/_messages.html.haml
.row
  .col-xs-10.col-xs-offset-1
    - flash.each do |name, msg|
      .alert{ :class => "alert-#{name}" }
        %button.close{ :data => { :dismiss => "alert" } } x
        = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{ type: :button, 'data-toggle' => :collapse, 'data-target' => "#bs-example-navbar-collapse-1" }
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Alpha Blog', root_path, class: 'navbar-brand', id: 'logo'

    / Navbar content
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right

        / links
        - if !logged_in?
          %li= link_to 'Articles', articles_path
        - if logged_in?
          %li.dropdown.open
            = link_to '#', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'true', 'class' => 'dropdown-toggle' do
              Articles
              %span.caret
            %ul.dropdown-menu{ role: :menu }
              %li= link_to 'View all articles', articles_path
              %li= link_to 'Create new article', new_article_path
        %li.nav-menu-item= link_to 'Authors', users_path
        %li.dropdown.open
          = link_to '#', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'true', 'class' => 'dropdown-toggle' do
            Categories
            %span.caret
          %ul.dropdown-menu{ role: :menu }
            %li= link_to 'All categories', categories_path
            %li.divider
            - Category.all.each do |category|
              %li= link_to "#{category.name}", category_path(category)
            - if logged_in? && current_user.admin?
              %li.divider
              %li= link_to "Create new category", new_category_path
        - if !logged_in?
          %li= link_to 'Log in', login_path 
          %li= link_to 'Sign up', signup_path

        / dropdown
        - if logged_in?
          %li.dropdown.open
            = link_to '#', 'data-toggle' => 'dropdown', 'role' => 'button', 'aria-expanded' => 'true', 'class' => 'dropdown-toggle' do
              Your Profile #{ "(admin)" if current_user.admin? }
              %span.caret
            %ul.dropdown-menu{ role: :menu }
              %li= link_to 'Edit your profile', edit_user_path(current_user)
              %li= link_to 'View your profile', user_path(current_user)
              %li.divider
              %li= link_to 'Log out', logout_path, method: :delete

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "AlphaBlog"
    %meta= csrf_meta_tags
    %meta= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %meta= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:name => 'viewport', :content => "width=device-width, initial-scale=1"}

  %body
    .flex
      = render 'layouts/navigation'
      = render 'layouts/messages'
      .container
        = yield
      = render 'layouts/footer'

app/views/pages/about.html.haml
.center
  %h1 About Alpha Blog
.center
  .well.about.col-md-8.col-md-offset-2
    %p "Alpha Blog was the very first blog, created sometime in the 8th or 9th century BCE. It was  used by poets such as Homer, Sappho, and Alcaeus; philosophers such as Socrates, Plato, and Aristotle; and dramatists such as Aeschylus, Euripides, and Sophocles. Over the centuries the site was maintained on secret servers located in hidden rooms of monasteries located around the Greek-speaking world."
    .line
    %article * I made this site using Ruby on Rails for the back end, with PostgreSQL for the database. For the front end, I used a bit of Bootstrap and CSS with minimal Sass. I also decided to use Haml for all templates instead of erb.

app/views/pages/home.html.haml
.center.jumbotron
  %h1.display-3 ALPHA BLOG
  = link_to 'Sign up now', signup_path , class: "btn btn-primary btn-lg"

app/views/shared/_errors.html.haml
- if obj.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
            prohibited this article from being saved:
          .panel-body
            %ul
            - obj.errors.full_messages.each do |msg|
              %li= msg

app/views/users/_form.html.haml
= render 'shared/errors', obj: @user
.row
  .col-xs-12
    = form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f|
      .form-group
        .col-form-label.col-sm-2
          = f.label :username
        .col-sm-8
          = f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true
      .form-group
        .col-form-label.col-sm-2
          = f.label :email
        .col-sm-8
          = f.email_field :email, class: "form-control", placeholder: "Enter email"
      .form-group
        .col-form-label.col-sm-2
          = f.label :password
        .col-sm-8
          = f.password_field :password, class: "form-control", placeholder: "Enter password"
      .form-group
        .center
          = f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-submit btn-lg")
    .center
      = link_to "Cancel request and return to articles listing", articles_path

app/views/users/edit.html.haml
%h1(align="center") Edit your account
= render 'form'

app/views/users/index.html.haml
%h1(align="center") All Alpha Bloggers
%div(align="center")= will_paginate
- @users.each do |user|
  %ul.listing
    .row
      .well.col-md-4.col-md-offset-4.center
        %li= link_to gravatar_for(user), user_path(user)
        %li.article-title= link_to user.username, user_path(user)
        %li
          %small= pluralize(user.articles.count, "article") if user.articles
          - if logged_in? and current_user.admin?
            %li= link_to 'Delete this user', user_path(user), method: :delete, data: { confirm: "Are you sure you want to permanently delete this user and all their articles?" }
%div(align="center")= will_paginate

app/views/users/new.html.haml
%h1(align="center") Sign up for Alpha Blog
= render 'form'

app/views/users/show.html.haml
%h1(align="center") Welcome to #{@user.username}'s page
.row
  .col-md-4.col-md-offset-4.center
    = gravatar_for @user, size: 150
%h4(align="center") #{@user.username}'s articles
.center= will_paginate @user_articles
= render 'articles/article', obj: @user_articles
.center= will_paginate @user_articles